name: pt_kharade_customer
description: PT Kharade Drycleaners & Laundry — customer app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  device_info_plus: ^12.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
